Restore prod
AlexMelov/FullStackApp pull request #64
Opened 2022-04-23 17:17 UTC by AlexMelov

2022-04-25 08:36 UTC, henryruhs requested changes

2022-04-25 08:36 UTC, henryruhs commented on frontend/.eslintrc
> +				"project":
Please rewrite to this - I think ** includes cypress folder aswell

```
"project":
[
	"**/tsconfig.json"
]
```

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/app/todo/form/form.component.spec.ts
> +			todos.forEach(todo =>
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/app/todo/list/list.component.spec.ts
> +	it('should create todo', async() =>
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/app/todo/todo.component.scss
> +.progress-bar
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/app/todo/todo.service.spec.ts
> +	it('should get all todos', async() =>
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/app/todo/todo.service.spec.ts
> +			todos.forEach(todo =>
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/src/ui.module.ts
> +		MatInputModule,
Should not be part of this PR

2022-04-25 08:36 UTC, henryruhs commented on frontend/tsconfig.json
>  		"skipLibCheck": true,
This might cause problems during lint!?

2022-04-26 07:35 UTC, AlexMelov commented on frontend/.eslintrc
> +				"project":
**/cypress/tsconfig.json not working, lint throws errors like he don't recognize the cypress syntax

2022-04-26 08:54 UTC, merged