Add transloco
AlexMelov/FullStackApp pull request #65
Opened 2022-04-23 17:17 UTC by AlexMelov

2022-04-25 08:54 UTC, henryruhs requested changes

2022-04-25 08:54 UTC, henryruhs commented on frontend/transloco.config.js
> +module.exports = {
Formatting is wrong but I think you can delete this file... it is not used

```
module.exports =
{
  rootTranslationsPath: 'src/assets/i18n/',
  langs: [ 'en', 'de', 'mk' ]
};
```

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/assets/i18n/en.json
> +{
The naming is not good... why is one button and the other removeButton? Also form is not a valid scope... it should be like that:

```
{
	"todo":
	{
		"inputPlaceholder": "Add todo title here",
		"buttonAdd": "Add Todo",
		"buttonRemove": "Remove Todo"
	}
}```

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/transloco-root.module.ts
> +        // Remove this option if your application doesn't support changing language in runtime.
Remove comment

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/transloco-root.module.ts
> +        defaultLang: 'en',
Default language should come from browser (navigator) else fallback to english if not detectable.

https://ngneat.github.io/transloco/docs/additional-functionality/#getbrowserlang

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/transloco-root.module.ts
> +		return this.http.get<Translation>(`${environment.baseUrl}/assets/i18n/${lang}.json`);
Please no template concatination ... I hate it :-)

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/transloco-root.module.ts
> +	getTranslation(lang : string) : Observable<Translation>
lang should be language

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/todo.component.ts
> +	constructor(private todoService : TodoService, public translocoService : TranslocoService)
This service has to be private aswell

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/todo.component.scss
> +.buttons
this is a `.wrapper-button` at it wraps buttons and is not a button. Add empty lines before and after each declaration

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/todo.component.scss
> +		min-width: 0;
not sure if min-widht is needed... I dont see it defined somewhere else

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/todo.component.scss
> +	button:first-child
Use proper classes like .button-select-en, .button-select-mk etc.

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/todo.component.scss
> +		background-image: url("https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg");
Never ever use external resources like that! Use a language pack from npm and include from node_modules

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/list/list.component.html
> +		<button mat-raised-button color="primary" (click)="removeTodo(todo.id)" data-test=remove-button>{{"form.removeButton"|transloco}}</button>
no double quote, missing spacing between variables and pipe

2022-04-25 08:54 UTC, henryruhs commented on frontend/src/app/todo/form/form.component.html
> +	<button matLine mat-raised-button (click)="addNewTodo()" data-test="add-button">{{"form.button"|transloco}}</button>
Please use single quote in variables - always and proper spacing

`{{ 'form.button' | transloco }}`

2022-04-25 08:54 UTC, henryruhs commented on frontend/package.json
> +		"@ngneat/transloco": "^4.0.0",
Please remove ^

2022-04-25 08:54 UTC, henryruhs commented on frontend/angular.json
>  							],
Dont remove the prod options - I suggest you merge into develop once the prod PR is merged aswell

2022-04-25 08:54 UTC, henryruhs commented on frontend/.eslintrc
> +			"parserOptions": {
Merge to develop once prod PR is done

2022-04-27 08:47 UTC, AlexMelov commented on frontend/src/app/todo/todo.component.scss
> +		background-image: url("https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg");
I was searching for npm's and I found one, they are suggesting this way as faster to get the link ```https://purecatamphetamine.github.io/country-flag-icons/3x2/``` 
and add the country name.svg at the end

2022-04-29 08:07 UTC, henryruhs requested changes

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.ts
> +	languages : Languages[] =
Move this to language.config.ts and fix the indent!

```
languages : Languages[] =
[
	{
		value: 'en',
		label: 'EN'
	},
	{
		value: 'de'
		label: 'DE'
	},
	{
		value: 'mk',
		label: 'MK'
	}
];
```

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.ts
> +	setLanguage(language : string) : void
This should not be a string, but Language type

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.model.ts
> +	value : string;
value should be Language type = 'en' | 'de' | 'mk'

rename language to label

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/transloco-root.module.ts
> +@Injectable({ providedIn: 'root' })
Two classes in one file is a NOGO !!!

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.spec.ts
> +		await TestBed.configureTestingModule({
{ on new line

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.scss
> +	background-position: right;
you repeat yourself 3 times here:

background-position: right;
background-repeat: no-repeat;

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.scss
> +.select-container
Rename to select-language

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.html
> +		<mat-label>Selected Language</mat-label>
It is funny, you implement translation feature and forget to translate the feature itself... replace hardcoded "Select Language" with transloco pipe

2022-04-29 08:07 UTC, henryruhs commented on frontend/package.json
> +		"e2e:stage": "cross-env-shell CYPRESS_APP_ENV=stage npm run e2e",
This changes are in develop already?

2022-04-29 08:07 UTC, henryruhs commented on .github/workflows/ci-stage.yml
> +                    vercel-token: ${{ secrets.VERCEL_TOKEN_STAGE }}
This changes are in develop already?

2022-04-29 08:07 UTC, henryruhs commented on .github/workflows/ci-stage.yml
> +            -   run: npm run build:stage --prefix ./backend
This changes are in develop already?

2022-04-29 08:07 UTC, henryruhs commented on frontend/src/app/todo/language/language.component.scss
> +	background-image: url('https://purecatamphetamine.github.io/country-flag-icons/3x2/DE.svg');
Do not use files from their temporary github page - it is not safe

2022-04-29 09:52 UTC, AlexMelov commented on .github/workflows/ci-stage.yml
> +            -   run: npm run build:stage --prefix ./backend
I do rebase on transloco with develop

2022-04-29 09:54 UTC, AlexMelov commented on .github/workflows/ci-stage.yml
> +                    vercel-token: ${{ secrets.VERCEL_TOKEN_STAGE }}
yes they are in develop

2022-04-29 09:54 UTC, AlexMelov commented on frontend/package.json
> +		"e2e:stage": "cross-env-shell CYPRESS_APP_ENV=stage npm run e2e",
yes

2022-04-29 15:13 UTC, henryruhs approved these changes

2022-04-29 15:13 UTC, merged